workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Clean and Get Flutter packages
        script: |
          flutter clean
          flutter pub get

      - name: Clean iOS Pods
        script: |
          cd ios
          rm -rf Pods
          rm Podfile.lock
          cd ..

      - name: Install CocoaPods
        script: |
          cd ios
          pod repo update
          pod install
          cd ..

      - name: Build iOS Release
        script: |
          flutter build ios --release --no-codesign -t lib/main.dart

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - goopstoot@gmail.com
