# ios/Podfile
platform :ios, '15.0'

# تعطيل CocoaPods Analytics
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end
